__use_yte__: true

datasets:
  admin_qc:
    path: ?input.admin_qc
    separator: "\t"

  ?if input.ascatstats:
    ascatstats:
      path: ?input.ascatstats
      separator: "\t"

  ?if input.tmb:
    tmb_table:
      path: ?input.tmb
      separator: "\t"

  ?if input.msi:
    msi_table:
      path: ?input.msi
      separator: "\t"


views:
  admin_qc:
    dataset: admin_qc
    render-table: {}

  ?if input.ascatstats:
    ascat_stats:
      dataset: ascatstats
      render-table: {}

  ?if input.tmb:
    tmb_table:
      dataset: tmb_table
      render-table: {}

  ?if input.msi:
    msi_table:
      dataset: msi_table
      render-table: {}
