tumor-normal:
  toplevel:
    # QC reports
    - "qc_report/{tumorid}_qc_stats.xlsx"
    # CNV report
    ## Ascat
    - "{tumor}/ascat/{tumorid}_ascat_plot.pdf"
    # SNV/INDEL calling
    ## TNscope
    - "{tumor}/tnscope/{tumorid}_TNscope_somatic.vcf.gz"
    - "{tumor}/tnscope/{tumorid}_TNscope_somatic.vcf.gz.csi"
    ## Pindel
    - "{tumor}/pindel/{tumorid}_pindel.xlsx"
    # SV calling
    ## Manta
    - "{tumor}/manta/{tumorid}_manta_somatic.vcf.gz"
    - "{tumor}/manta/{tumorid}_manta_somatic.vcf.gz.csi"
    - "{tumor}/manta/{tumorid}_manta_somatic_Summary.xlsx"

  IGV_files:
    # Read mapping
    - "{tumor}/realign/{tumorid}_REALIGNED.bam"
    - "{tumor}/realign/{tumorid}_REALIGNED.bam.bai"
    - "{tumor}/realign/{tumorid}_REALIGNED.bam.tdf"
    - "{normal}/realign/{normalid}_REALIGNED.bam"
    - "{normal}/realign/{normalid}_REALIGNED.bam.bai"
    - "{normal}/realign/{normalid}_REALIGNED.bam.tdf"
    # CNV_seg
    ## Ascat
    - "{tumor}/ascat/{tumorid}_ascat_CN_smooth_IGV.seg"
    - "{tumor}/ascat/{tumorid}_ascat_CN_call_IGV.seg"
    - "{tumor}/ascat/{tumorid}_ascat_BAF_IGV.seg"
    ## Canvas
    - "{tumor}/canvas/{tumorid}_canvas_somatic_called.seg"
    - "{tumor}/canvas/{tumorid}_canvas_somatic_observed.seg"
    - "{tumor}/reports/{tumorid}_baf.igv"
    - "{normal}/canvas/{normalid}_canvas_germline_called.seg"
    - "{normal}/canvas/{normalid}_canvas_germline_observed.seg"
    - "{normal}/reports/{normalid}_baf.igv"

  SNV_INDEL_germline:
    # SNV/INDEL calling
    ## TNscope
    - "{normal}/dnascope/{normalid}_DNAscope_germline.vcf.gz"
    - "{normal}/dnascope/{normalid}_DNAscope_germline.vcf.gz.csi"

  CNV_vcf:
    # CNV calling
    ## Canvas
    - "{tumor}/canvas/{tumorid}_canvas_somatic.vcf.gz"
    - "{tumor}/canvas/{tumorid}_canvas_somatic.vcf.gz.csi"
    - "{tumor}/canvas/{tumorid}_canvas_somatic_filt.vcf.xlsx"
    - "{normal}/canvas/{normalid}_canvas_germline.vcf.gz"
    - "{normal}/canvas/{normalid}_canvas_germline.vcf.gz.csi"

  pipeline_info:
    - "tool_versions.yaml"
    - "logs/{tumorid}.log"
    - "logs/report.html"
    - "configs/filters.yaml"

  not_copied:
    # Note: the following files are not copied to webstore but are added as a target to include them in the workdir
    # The exception for these files is in copy_results() function in launch_snakemake.py
    - "qc_report/{tumorid}_qc_stats_wgsadmin.xlsx"

tumor-only:
  toplevel:
    # QC reports
    - "qc_report/{tumorid}_qc_stats.xlsx"
    # CNV report
    ## Ascat
    - "{tumor}/ascat/{tumorid}_ascat_plot.pdf"
    # SNV/INDEL calling
    ## TNscope
    - "{tumor}/tnscope/{tumorid}_TNscope_somatic_vep_gnomadfilt.vcf.gz"
    - "{tumor}/tnscope/{tumorid}_TNscope_somatic_vep_gnomadfilt.vcf.gz.csi"
    ## Pindel
    - "{tumor}/pindel/{tumorid}_pindel.xlsx"
    # SV calling
    ## Manta
    - "{tumor}/manta/{tumorid}_manta_somatic.vcf.gz"
    - "{tumor}/manta/{tumorid}_manta_somatic.vcf.gz.csi"
    - "{tumor}/manta/{tumorid}_manta_somatic_Summary.xlsx"

  IGV_files:
    # Read mapping
    - "{tumor}/realign/{tumorid}_REALIGNED.bam"
    - "{tumor}/realign/{tumorid}_REALIGNED.bam.bai"
    - "{tumor}/realign/{tumorid}_REALIGNED.bam.tdf"
    # CNV_seg
    ## Ascat
    - "{tumor}/ascat/{tumorid}_ascat_CN_smooth_IGV.seg"
    - "{tumor}/ascat/{tumorid}_ascat_CN_call_IGV.seg"
    - "{tumor}/ascat/{tumorid}_ascat_BAF_IGV.seg"
    ## Canvas
    - "{tumor}/canvas/{tumorid}_canvas_tumoronly_called.seg"
    - "{tumor}/canvas/{tumorid}_canvas_tumoronly_observed.seg"
    - "{tumor}/reports/{tumorid}_baf.igv"

  CNV_vcf:
    # CNV calling
    ## Canvas
    - "{tumor}/canvas/{tumorid}_canvas_tumoronly.vcf.gz"
    - "{tumor}/canvas/{tumorid}_canvas_tumoronly.vcf.gz.csi"
    - "{tumor}/canvas/{tumorid}_canvas_tumoronly_filt.vcf.xlsx"

  pipeline_info:
    - "tool_versions.yaml"
    - "logs/{tumorid}.log"
    - "configs/filters.yaml"

  not_copied:
    # Note: the following files are not copied to webstore but are added as a target to include them in the workdir
    # The exception for these files is in copy_results() function in launch_snakemake.py
    - "qc_report/{tumorid}_qc_stats_wgsadmin.xlsx"

normal-only:
  toplevel:
    # QC reports
    - "qc_report/{normalid}_qc_stats.xlsx"
    # SNV/INDEL calling
    ## DNAScope
    - "{normal}/dnascope/{normalid}_DNAscope_germline.vcf.gz"
    - "{normal}/dnascope/{normalid}_DNAscope_germline.vcf.gz.csi"

  IGV_files:
    # Read mapping
    - "{normal}/realign/{normalid}_REALIGNED.bam"
    - "{normal}/realign/{normalid}_REALIGNED.bam.bai"
    - "{normal}/realign/{normalid}_REALIGNED.bam.tdf"
    # CNV_seg
    ## Canvas
    - "{normal}/canvas/{normalid}_canvas_germline_called.seg"
    - "{normal}/canvas/{normalid}_canvas_germline_observed.seg"
    - "{normal}/reports/{normalid}_baf.igv"

  CNV_vcf:
    # CNV calling
    ## Canvas
    - "{normal}/canvas/{normalid}_canvas_germline.vcf.gz"
    - "{normal}/canvas/{normalid}_canvas_germline.vcf.gz.csi"

  pipeline_info:
    - "tool_versions.yaml"
    - "logs/{normalid}.log"
    - "configs/filters.yaml"

  not_copied:
    # Note: the following files are not copied to webstore but are added as a target to include them in the workdir
    # The exception for these files is in copy_results() function in launch_snakemake.py
    - "qc_report/{normalid}_qc_stats_wgsadmin.xlsx"
